name: Chairs
version: 4.2
description: Let players sit on blocks.
website: http://dev.bukkit.org/bukkit-plugins/chairsreloaded/
authors: 
 - spoothie
 - cnaude
 - _Shevchik_
 - Pugabyte
main: com.cnaude.chairs.core.Chairs
commands:
    chairs:
        description: Various commands for Chairs.
        usage: |
          /<command> reload - reloads the configuration
          /<command> off  - disable chairs for self
          /<command> on - enable chairs for self
          /<command> sit - Sit on a chair, bypassing the sign check
permissions:
  chairs.*:
    description: Gives access to all Chairs commands
    children:
      chairs.sit: true
      chairs.reload: true
  chairs.sit:
    description: Allows you to sit on chair
    default: true
  chairs.sit.command:
    description: Allows you to sit on chair
    default: true
  chairs.reload:
    description: Allows you to reload Chairs Configuration
    default: op
  
